mon = int(input("Enter the Sales for Monday :"))
tue = int(input("Enter the Sales for Tuesday :"))
wed = int(input("Enter the Sales for Wednesday :"))
thur = int(input("Enter the Sales for Thursday :"))
fri = int(input("Enter the Sales for Friday :"))
sat = int(input("Enter the Sales for Saturday :"))
sun = int(input("Enter the Sales for Sunday :"))
total_sales = (mon+tue+wed+thur+fri+sat+sun)
print(total_sales)
aver = total_sales/7
print(aver)
minimum = min(mon,tue,wed,thur,fri,sat,sun)
maximum = max(mon,tue,wed,thur,fri,sat,sun)
print(minimum,maximum)